#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("asthanarht.expendedView.Resource", IsApplication=true)]

namespace asthanarht.expendedView
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010009
			public const int animation_duration = 2130771977;
			
			// aapt resource value: 0x7f010004
			public const int indicator_margin_left = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int indicator_margin_right = 2130771973;
			
			// aapt resource value: 0x7f010003
			public const int indicator_size = 2130771971;
			
			// aapt resource value: 0x7f010000
			public const int item_layout = 2130771968;
			
			// aapt resource value: 0x7f010002
			public const int separator_layout = 2130771970;
			
			// aapt resource value: 0x7f010007
			public const int show_animation = 2130771975;
			
			// aapt resource value: 0x7f010006
			public const int show_indicator = 2130771974;
			
			// aapt resource value: 0x7f010008
			public const int start_collapsed = 2130771976;
			
			// aapt resource value: 0x7f010001
			public const int sub_item_layout = 2130771969;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int expanding_item_circle_base = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050005
			public const int base_list_layout = 2131034117;
			
			// aapt resource value: 0x7f050007
			public const int base_separator_stub = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int base_sub_list_layout = 2131034118;
			
			// aapt resource value: 0x7f050004
			public const int icon_indicator_bottom = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int icon_indicator_middle = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int icon_indicator_top = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int indicator_container = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int indicator_image = 2131034114;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int expanding_item_base_layout = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] ExpandingItem = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977};
			
			// aapt resource value: 9
			public const int ExpandingItem_animation_duration = 9;
			
			// aapt resource value: 4
			public const int ExpandingItem_indicator_margin_left = 4;
			
			// aapt resource value: 5
			public const int ExpandingItem_indicator_margin_right = 5;
			
			// aapt resource value: 3
			public const int ExpandingItem_indicator_size = 3;
			
			// aapt resource value: 0
			public const int ExpandingItem_item_layout = 0;
			
			// aapt resource value: 2
			public const int ExpandingItem_separator_layout = 2;
			
			// aapt resource value: 7
			public const int ExpandingItem_show_animation = 7;
			
			// aapt resource value: 6
			public const int ExpandingItem_show_indicator = 6;
			
			// aapt resource value: 8
			public const int ExpandingItem_start_collapsed = 8;
			
			// aapt resource value: 1
			public const int ExpandingItem_sub_item_layout = 1;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
